### ISSUE TITLE
Generating the Palette Colors for Figma

### ISSUE THREAD

**Issue by porada** [Automattic/color-studio#10]
Right now, Color Studio covers Sketch users. It generates the palette file and the utility extension that generates a set of reusable color styles and symbols within a Sketch file.

Assuming they make sense, is there a way to automatically create the equivalents for Figma?

**Comment by porada** [comment]
@drw158 @jasmussen, since you have much more experience with Figma than me, can you weigh in on this issue?

**Comment by drw158** [comment]
Not possible afaik at the moment, but their plugin api is in beta right now. It might be possible to write a  new figma "file" with the color styles.

**Comment by porada** [comment]
Yep, that’s exactly what the Sketch extension does.

**Comment by jasmussen** [comment]
I would indeed watch this plugin space ;)

**Comment by porada** [comment]
Closing. Given how many projects depend on the shared design library, it’s probably safer to update the colors manually.
