### ISSUE TITLE
Rename Airo

### ISSUE THREAD

**Issue by haszari** [Automattic/color-studio#13]
The airo names don't mention "blue", even though it's clearly a kind of blue. Would it be clearer to name it "Airo Blue"?

**Comment by porada** [comment]
I wanted us to be able to use single-word names, but I hear you.

Inspired by @drw158’s findings mentioned in #11, I’ve been thinking about renaming Airo to Sky, which sounds more like a kind of blue. Thoughts?

```
ay-iro → airo → aero → sky
```

**Comment by drw158** [comment]
I agree. I like the idea of Airo, but for usability of the system, Sky seems like a nice alternative. It will be easier to understand if you are just looking at the code. Another option is Cyan.

While on the subject, I think the same applies to Celadon, which could be Teal instead.

Ideas:

![Screen Shot 2019-07-03 at 10 51 34 AM](https://user-images.githubusercontent.com/618551/60606212-90123d80-9d80-11e9-9652-1e7062d20f50.png)

**Comment by porada** [comment]
Cyan might be misleading since it’s generally perceived as a brighter shade of blue and our brand color is more subdued. Sky is more opinionated, especially when we can trace it back to _ay-iro._

**Comment by porada** [comment]
I’d like to keep Celadon, though. I had the exact same puzzle with v1 as it lies somewhere between blueish Teal and greenish Mint. Apps that name colors define Celadon 50 as Deep Sea, but that’s too abstract for a design system.

Celadon is rarely used in Calypso and we’ve got used to its name on the brand side of things.
