### ISSUE TITLE
Bump the “Guaranteed Accessibility” Shade Level to 60

### ISSUE THREAD

**Issue by porada** [Automattic/color-studio#14]
Right now, 50 is the shade level that guarantees accessibility against white (contrast ratio ≥ 4.5). This obviously affects our yellow (and orange to a lesser extent).

Trying to decide if we should add examples to test against, I’ve been looking at the ways we depend on yellow in our apps. The screen below is a probably the best example of how we use it.

![Activity Screenshot](https://user-images.githubusercontent.com/2060580/60680453-af49c180-9e8b-11e9-8a4c-9327552f4257.png)

With our brand colors being subdued and colder, yellow is primarily used for [communicating status](https://color-studio.blog/examples/calypso-components.html). We never use yellow for text and we don’t use orange almost anywhere in the default color scheme.

Given that there is no way around accessible yellow being muddy and introducing another lighter shade to all the palette colors would make the transition from v1 to v2 much more painful, I’d like to suggest the following.

Let’s bump the “guaranteed accessibility” shade level to 60 at the cost of yellow’s and orange’s brightness consistency with the rest of the colors.

* All other colors would be untouched, maintaining the lower barrier of update from v1 to v2.
    * There would be no immediate need to update our existing UI controls to 60.
* Yellow and orange would look like the actual colors and be better optimized for the common use case mentioned above.
   * Yellow 50 and Orange 50 would pass at least AA Large.
   * Yellow 60 and Orange 60 would pass AA.
* Guaranteed accessibility would still apply. Those people that would want to take advantage of the interchangeable colors would start with shades 60 or higher.

**Comment by porada** [comment]
Pinging @cburton4 @drw158 @mattmiklic @nheagy @simison. This also affects #11.

**Comment by porada** [comment]
I managed to obtain a better accessible Orange 50, which makes Yellow the only exception. The side effect of this solution is a more visible difference between Orange 60 and Yellow 60 (which both get brown as they get dark).

![Color ramps](https://user-images.githubusercontent.com/2060580/60815497-0efbe180-a198-11e9-93aa-9afbae0b9821.png)

We’ll still have to find accessible workarounds to our components, but it’s going to be easier now that the palette colors will be more _true:_

<img width="1440" alt="Activity" src="https://user-images.githubusercontent.com/2060580/60816367-e96fd780-a199-11e9-91a5-56cc30c7df8c.png">

![Notice bars](https://user-images.githubusercontent.com/2060580/60816014-0e177f80-a199-11e9-9f2f-31cab6e87cd8.png)

The orange warning bar is just an example that doesn’t exist in our app yet. The only orange components in Calypso right now are the [Business plan icon](https://color-studio-ly42te5cu.now.sh/examples/marketing-icons.html) and everything around it. (Please note that you can browse the entire project under this link.)

**Comment by mattmiklic** [comment]
These are looking good to my eyes. 👍

**Comment by drw158** [comment]
I like that Orange looks more orange and Yellow looks more yellow. I think I see what you are saying about there being a bigger difference between Orange 60 and Yellow 60, but after your changes, they look closer together on the color wheel. I guess they are closer together in hue, but more different in value.

![Screen Shot 2019-07-08 at 10 28 20 AM](https://user-images.githubusercontent.com/618551/60822473-1fe22e00-a16b-11e9-846c-1367cbacf6d7.png)

As you know, I ilke shifting the accessible shade to 60, especially if we plan on shifting all of the colors to 60. This gives us more lighter shades, and it allows for Orange and Yellow to look more like orange and yellow.

Now that Yellow is the only exception, I question the need to shift the accessible shade to 60. I'm not sure I understand the benefit. It looks like the [Activity example](https://color-studio-ly42te5cu.now.sh/examples/android-bright-theme.html) is using 30 for yellow and 40 for the other status colors. Weren't we doing that anyway before this change to make sure yellow looks more yellow for colorblind folks? Is making Yellow the exception worth the inconsistency?

**Comment by porada** [comment]
> Again, I'm all for shifting Yellow to 60 if we are going to also shift the other colors, but for this v2 I'm not sure.

I’ve played with the examples that rely on yellow and I think I understand the feedback we’re getting.

It all comes down to how many shades you can comfortably use below and above shade 50:

* AA-accessible Yellow 50 is always muddy. Mathematically speaking, accessible yellow is an oxymoron.
* AA Large-accessible Yellow 40 is also muddy—a little less muddy, but still doesn’t look yellow.
* Yellow 60 and above is pure brown and I can’t see where we’d use it (apart from some labels that may accompany bright yellow elements). The truth is we only use yellow for warnings.
* Yellow 0 and 10 are too bright. They’re great for marketing use (which is something we’ve been doing), their luminosity is too low to achieve anything meaningful in a UI.

This leaves us with Yellow 20 and 30, which we the only two shades that are still yellow and that we can comfortably use. That’s very few and they don’t look that good either. Opening that up by even one step, adds more usable yellow shades and improves their “yellowness.”

With Yellow being the only exception, I’d even go further and bump accessible Yellow to 70. We need yellow, not brown.

I know you’re a fan of Mineral UI, but there’s a reason how ended up with consistent “Guaranteed Accessibility.” They don’t have yellow.

**Comment by porada** [comment]
> I think I see what you are saying about there being a bigger difference between Orange 60 and Yellow 60, but after your changes, they look closer together on the color wheel.

That’s the trick. Accessible orange looks like orange when it gets closer to yellow’s hue angles. That what gives it the vibrancy—otherwise it’s going to look brown, too.
