### ISSUE TITLE
Make 0 colors brighter

### ISSUE THREAD

**Issue by davewhitley** [Automattic/color-studio#18]
While working on [this post](https://make.wordpress.org/design/2019/11/26/proposal-a-new-color-palette-for-wordpress/), I realized that the 0 colors of some hues were not quite bright enough to match the brightness of Gray 0

## Before

![image](https://user-images.githubusercontent.com/618551/69742611-b0adac00-1102-11ea-9963-95d9daefd7d0.png)
![image](https://user-images.githubusercontent.com/618551/69742629-b86d5080-1102-11ea-87e8-a31076e82905.png)

## After

![image](https://user-images.githubusercontent.com/618551/69742658-c327e580-1102-11ea-8b8e-c71d7b01c3a0.png)
![image](https://user-images.githubusercontent.com/618551/69742691-cb802080-1102-11ea-96c9-030ff3412ace.png)

I was able to achieve this by turning up the luminance to 98-99.

**Comment by porada** [comment]
@davewhitley, I’m happy you’re taking the full advantage of the color characteristics with the .org palette, but the main difference between the .org palette and ours is that we also use it also for marketing and other non-product cases.

More vibrant 0 shades are increasingly difficult to use on darker backgrounds. We need to be able use color to demonstrate visually hierarchy (imagine a white heading and a piece of text below it using a 0 or 5 shade). This is actually the reason they were toned down a little. Those fixes also improve the app UI in dark mode.
