### ISSUE TITLE
Make yellow more orange

### ISSUE THREAD

**Issue by davewhitley** [Automattic/color-studio#19]
By switching the hue start and end values, we can make Yellow a bit less brown.

```
hue_start: 50,
hue_end: 40,
```
## Before

![Screen Shot 2019-11-27 at 10 48 43 AM](https://user-images.githubusercontent.com/618551/69743112-7f81ab80-1103-11ea-9aee-85fce7789c69.png)

## After

![Screen Shot 2019-11-27 at 10 48 18 AM](https://user-images.githubusercontent.com/618551/69743127-84465f80-1103-11ea-8979-feca939c1ced.png)

**Comment by davewhitley** [comment]
This causes some minor refactoring of lum and sat. Here are the new values that I used:

```
     sat_steps: [
          8, 30, 51.9, 75, 89.4, 100, 100, 100, 100, 100, 100, 100
        ],
        lum_steps: [
          99, 96, 95, 94, 86, 74, 60, 46, 38, 29, 21, 13
        ]
```

**Comment by porada** [comment]
I like those updates, @davewhitley. As I already mentioned somewhere on Slack, the initial versions of Yellow were actually more orange for that exact reason.

With my comment on #18 in mind, we’d have to adjust the brighter end a bit, but I’ll be pinging you about that. 🙂
