### ISSUE TITLE
Remove Muriel name from generated files

### ISSUE THREAD

**Issue by drw158** [Automattic/color-studio#2]
Since we don't want to confuse what is Muriel and what isn't, let's remove the Muriel name from this project (this color palette is a8c specific).

**Comment by porada** [comment]
@drw158, Muriel embraced this color palette, so is this issue still valid?

Given how the color format files are generated, I’d rather not introduce a customizable prefix. But if the very presence of `muriel` is problematic in any way, now is the best time to change it (e.g. to `automattic` or `studio`).

**Comment by drw158** [comment]
Hm, I think it would be great to find a more general term, or perhaps use `automattic` since that is the scope of the tool right now. Some ideas:

- no prefix?
- automattic
- color-studio
- cs
- studio

**Comment by porada** [comment]
Went with `studio`. It’s a single word that doesn’t exclude other companies from using the project.
