### ISSUE TITLE
Turn down luminance on on Blue 30 and Gray 30

### ISSUE THREAD

**Issue by davewhitley** [Automattic/color-studio#20]
As described in [this post](https://make.wordpress.org/design/2019/11/26/proposal-a-new-color-palette-for-wordpress/), if we turn down the lum value a step or two, we can achieve a 3:1 contrast ratio against both white and Gray 0. It's very subtle, so it shouldn't affect things visually.

New Blue 30 lum value: `83`
New Gray 30 lum value: `58`

**Comment by porada** [comment]
Thanks for the suggestion, @davewhitley.

Both Blue 30 and Gray 30 already score AA Large against white. I like the idea of shades 30 having accessible contrast against 0s, so I’ll review the cases and possibly implement those changes along a future round of color updates. 👍

Leaving this open for now.

**Comment by porada** [comment]
```
$ jest --all
 FAIL  test/palette.test.js
  ● dark mode accessibility › special cases

    expected contrast ratio between #e9eff5 and #4f94d4 (2.78) to be ≥ 3

      113 |   test('special cases', () => {
      114 |     expect(3.0).toBeContrastRatioBetween(PALETTE['Gray 0'], PALETTE['Gray 30'])
    > 115 |     expect(3.0).toBeContrastRatioBetween(PALETTE['Blue 0'], PALETTE['Blue 30'])
          |                 ^
      116 |   })
      117 | })
      118 |
```

Looks like the updated blue doesn’t pass against `Blue 0`. Grays works fine.

To be honest, I don’t see much value in keeping Blue 30 compliant against lighter Gray 0. And given the fact we might be changing adjust blues again soon, I’m only going to update Gray 30.
