### ISSUE TITLE
Add option for css custom properties

### ISSUE THREAD

**Issue by drw158** [Automattic/color-studio#3]
It would be great if we had the option to use css custom properties instead of scss variables. Or, let css custom properties be the default. Not sure if you could generate 2 separate files, or maybe it'd be all in one file, or something else.

**Comment by porada** [comment]
This felt like a low-hanging fruit, so I [added it](dist/color-properties.css).

The custom properties are still prefixed with `muriel` for consistency, before #2 is solved.
