### ISSUE TITLE
Which brand colour shade to use?

### ISSUE THREAD

**Issue by simison** [Automattic/color-studio#4]
Yay! I just noticed brand colours here! https://github.com/Automattic/color-studio/commit/546e4ed57ec2426246049096fbd3064e1d4ecfb0#diff-b933be50b3db86b8961f941ed1c26833R10

Excellent!

Now, shouldn't we just have one version of those colours? I expected to find `color-jetpack-green`, not 11 shades of it. Which one is the "real one" I can use? I'm I allowed to use all of these in the project?

cc @joanrho

**Comment by porada** [comment]
I’m closing this issue as the color guidelines aren’t really a part of this tool.
