### ISSUE TITLE
provide a flat json index of color name to color value / info

### ISSUE THREAD

**Issue by haszari** [Automattic/color-studio#8]
The current json interface is quite complex and nested. To use it in code, you effectively need to "search" for the color name you want. This search is complicated by the fact that it's nested (color name / color intensity). 

It would be super useful to flatten the structure and use the full color id as key, so lookups for standard colors are trivial.

Example: 

```js
// colors.json (flat version)
{
  //... 
  'hot-pink-500': {
        "name": "Hot Pink 500",
        "value": "#d52c82",
        "_meta": {
          "baseColor": true,
          "baseName": "Hot Pink",
          "colorFormula": "secondary",
          "shadeIndex": 500
        }
  }
  //... 
}
```

```js
// client code - e.g. PostCSS config using Muriel / Color Studio colors
// (no warranties with this color scheme!!)
const a8cColorStudio = require( 'color-studio' );

module.exports = {
	plugins: [
		require( '@wordpress/postcss-themes' )( {
			defaults: {
				primary: a8cColorStudio[ 'hot-pink-500' ].value,
				secondary: a8cColorStudio[ 'hot-blue-500' ].value,
				toggle: a8cColorStudio[ 'hot-green-500' ].value,
				button: a8cColorStudio[ 'hot-orange-500' ].value,
				outlines: a8cColorStudio[ 'hot-red-500' ].value,
			},
			themes: {
			},
		} ),
		require( 'autoprefixer' )(),
		require( 'postcss-color-function' ),
	],
};
```

**Comment by porada** [comment]
Honestly, I never envisioned the internal JSON file being used externally, but you proved me wrong.

With that said, I hear you and this will the new default in the next major version (which is coming soon). ✌️

**Comment by haszari** [comment]
@porada Super ace! What's the rough timeline for "coming soon"?

**Comment by haszari** [comment]
Oo, I see a PR (?) in progress!

**Comment by porada** [comment]
The way I see this, you should probably carry on with whatever you have right now. The new colors will be “incompatible” with the old palette, so they’ll probably require taking a step back to design anyway.

Meanwhile, I’d suggest you remedy this API issue with a utility like [`toNamedColorCollection`](https://github.com/Automattic/color-studio/blob/next/utilities/to-named-color-collection.js) found in this repo ([here’s a test](https://github.com/Automattic/color-studio/blob/next/test/utilities/to-named-color-collection.test.js) if you need it too).

**Comment by haszari** [comment]
> The way I see this, you should probably carry on with whatever you have right now. The new colors will be “incompatible” with the old palette, so they’ll probably require taking a step back to design anyway.

Where can I hear more about the palette changing? Just curious about the bigger picture. I'm using color-studio for implementing new designs/pages so we might want to use the "new" palette or names (cc @Garance91540 ).
