### ISSUE TITLE
Translucent Colors

### ISSUE THREAD

**Issue by porada** [Automattic/color-studio#9]
We need a set of semi-transparent white shades as a utility. Those steps should be consistent with the rest of the palette.

Would we also benefit from the black ones?

**Comment by drw158** [comment]
Hm I can only think of scrims and overlays needing a black transparency. 

What would the white ones be used for, and what would the utility look like?

**Comment by porada** [comment]
We use translucent white for things like button or container [outlines](https://cloudup.com/caMQ0-TwcIK) so that they could work on top of different background colors. Defining an outlined button with a white label and a solid border color for each color in the palette would be an overkill and a performance burden, so we fall back to translucency in cases like that. I think we’ve used white for an overlay layer, too.

I imagine we’d add white and black (Gray 100) strips of translucent colors, going from fully transparent to fully opaque—graded in a way that’s somewhat consistent with the other palette colors.

Since mobile teams fall back to their respective system colors in cases like that, those would be primarily used on the web.

**Comment by porada** [comment]
Closing. Looks like there’s no need to standardize those.
